apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "koslog-vue-site"
  description: "SPA website built with vuejs"
  annotations:
    github.com/project-slug: officialsamtech/koslog-vue-site
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://vuejs.org/
      title: Vue.js Koslog
      icon: site
  tags:
    - website
    - vue
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/koslog-ui"